### ISSUE TITLE
add c++

### ISSUE THREAD

**Issue by mightymariomanlol** [Lexikos/CLR.ahk#1]
when will there 
be c++ with this library?

**Comment by Lexikos** [comment]
Never.

`CLR_CompileAssembly` uses the functionality of a `CodeDomProvider` derived class to invoke the respective compiler. From the very beginning, all languages for which the framework provides such a class have been supported, and no further languages can be supported.

As far as I know, .NET Framework (runtime, not SDK) does not include a C++ compiler, and the [documentation](https://learn.microsoft.com/en-us/dotnet/api/system.codedom.compiler.codedomprovider?view=windowsdesktop-7.0) indicates that the standard CodeDomProviders only cover C#, JScript and VB.

If I recall correctly, newer .NET versions do not include these capabilities for any language by default; it is necessary to download additional packages to compile code on the fly. But then, newer .NET versions aren't included with Windows by default anyway.
