### ISSUE TITLE
CLR_LoadLibrary() returning empty string

### ISSUE THREAD

**Issue by MisterrOrange** [Lexikos/CLR.ahk#2]
That's my code:

#include CLR.ahk
MsgBox, % CLR_LoadLibrary("C:\Users\admin\Desktop\MyDll.dll")

**Comment by Lexikos** [comment]
I forgot that this repository exists. Apparently it is for the v2 version of CLR.ahk, which you are clearly not using.

CLR_LoadLibrary v1.x is expected to return an empty string if it cannot load the assembly.

MsgBox v1.x is expected to display blank if you pass it an object. Your code is therefore expected to always display a blank box, even if the assembly loaded successfully.

If the script is unable to load a dll, it is a problem with the dll or environment.
